### ISSUE TITLE
AdvSND: Modify tunnel geometry

### ISSUE THREAD

**Issue by olantwin** [SND-LHC/sndsw#108]
In Floor.cxx we will need to modify the TI18 geometry to make space for the magnet. This cam most likely be done by subtracting suitably sized shapes from the TGeoCompositeShapes making up TI18 currently.

**Comment by olantwin** [comment]
I think this is done? @dcentanni

**Comment by dcentanni** [comment]
> I think this is done? @dcentanni

Not as it was supposed to. So far, a shape (`DetShape`) bigger that the detector volume is subtracted to the Tunnel shape. As done in [this](https://github.com/SND-LHC/advsndsw/commit/a007ed420a6b5938e9d3938ab303f7ad167d585b) commit.

**Comment by olantwin** [comment]
Then let's open an issue for the proper implementation in the advsndsw repo.
