### ISSUE TITLE
running snd sw

### ISSUE THREAD

**Issue by ThomasRuf** [SND-LHC/sndsw#12]
I finally succeeded building sndsw. Trying to run  python -i sndsw/macro/run_simScript.py --shiplhc -n 10, gives me the following warnings and error:

1)
```
Warning in <TInterpreter::ReadRootmapFile>: class  ShipCave found in shipLHC.so  is already in ShipPassive.so 
Warning in <TInterpreter::ReadRootmapFile>: class  ShipGeoCave found in shipLHC.so  is already in ShipPassive.so
```

This is not good. I guess the snd classes should be renamed in TI18Cave?

2)
Do first: source config.[c]sh  

This is triggered by  shipRoot_conf.py
```
# Try to check if config has been executed...
if os.environ.get('FAIRSHIP_ROOT', '') == '' and os.environ.get('Linux_Flavour_', '') == '':
```

FAIRSHIP_ROOT is probably not needed, but FAIRSHIP environment variable is needed here, 
shipRoot_conf.configure:
`ROOT.gROOT.ProcessLine('#include "'+os.environ["FAIRSHIP"]+'/shipdata/ShipGlobals.h"')`

What should be the solution? 

3)
Setup for ship LHC measurement has been set
```
Traceback (most recent call last):
  File "sndsw/macro/run_simScript.py", line 214, in <module>
    ship_geo = ConfigRegistry.loadpy("$FAIRSHIP/geometry/shipLHC_geom_config.py")
  File "/media/disk1/SNDBuild/sw/ubuntu2004_x86-64/sndsw/master-1/python/ShipGeoConfig.py", line 50, in loadpy
    return ConfigRegistry.loadpys(fh.read(), **kwargs)
  File "/media/disk1/SNDBuild/sw/ubuntu2004_x86-64/sndsw/master-1/python/ShipGeoConfig.py", line 55, in loadpys
    exec(string_unixlf, kwargs)
  File "<string>", line 12
    c.EmulsionDet.wall= 5
                        ^
TabError: inconsistent use of tabs and spaces in indentation
```

no idea how to fix this.

**Comment by olantwin** [comment]
> I finally succeeded building sndsw. Trying to run python -i sndsw/macro/run_simScript.py --shiplhc -n 10, gives me the following warnings and error:
> 
> 
> ```
> Warning in <TInterpreter::ReadRootmapFile>: class  ShipCave found in shipLHC.so  is already in ShipPassive.so 
> Warning in <TInterpreter::ReadRootmapFile>: class  ShipGeoCave found in shipLHC.so  is already in ShipPassive.so
> ```
> 
> This is not good. I guess the snd classes should be renamed in TI18Cave?

Yes, we should rename this. Ideally as a more long-term solution, I would like to put all SND things into it's own namespace, as we also had some other issues in the past with reusing names from FairRoot in FairShip.

**Comment by olantwin** [comment]
> Do first: source config.[c]sh
> 
> This is triggered by shipRoot_conf.py
> 
> ```
> # Try to check if config has been executed...
> if os.environ.get('FAIRSHIP_ROOT', '') == '' and os.environ.get('Linux_Flavour_', '') == '':
> ```
> 
> FAIRSHIP_ROOT is probably not needed, but FAIRSHIP environment variable is needed here,
> shipRoot_conf.configure:
> `ROOT.gROOT.ProcessLine('#include "'+os.environ["FAIRSHIP"]+'/shipdata/ShipGlobals.h"')`
> 
> What should be the solution?

I don't understand this part. Could you please elaborate?

**Comment by olantwin** [comment]
> Setup for ship LHC measurement has been set
> 
> ```
> Traceback (most recent call last):
>   File "sndsw/macro/run_simScript.py", line 214, in <module>
>     ship_geo = ConfigRegistry.loadpy("$FAIRSHIP/geometry/shipLHC_geom_config.py")
>   File "/media/disk1/SNDBuild/sw/ubuntu2004_x86-64/sndsw/master-1/python/ShipGeoConfig.py", line 50, in loadpy
>     return ConfigRegistry.loadpys(fh.read(), **kwargs)
>   File "/media/disk1/SNDBuild/sw/ubuntu2004_x86-64/sndsw/master-1/python/ShipGeoConfig.py", line 55, in loadpys
>     exec(string_unixlf, kwargs)
>   File "<string>", line 12
>     c.EmulsionDet.wall= 5
>                         ^
> TabError: inconsistent use of tabs and spaces in indentation
> ```
> 
> no idea how to fix this.

This is fixed in #10

**Comment by ThomasRuf** [comment]
What had been the reason to copy ShipCave and ShipGeoCave into shipLHC?
They look identical. Removing these files from the shipLHC directory has no effect on running the simulation.

**Comment by olantwin** [comment]
@abuonaura said it was needed as a workaround to some problem. I agree that they shouldn't be needed (but maybe there is something I'm not considering)

**Comment by ThomasRuf** [comment]
a diff showed no difference in the cxx files. I removed them from CMakeLists.txt, and it compiled and run happily.

**Comment by olantwin** [comment]
I think everything here is taken care off (at least with a temporary solution). I suggest we close this issue and discuss in separate issues such as #20 for further improvements.
