### ISSUE TITLE
aliBuild: error: Default `o2' does not exists

### ISSUE THREAD

**Issue by 71year** [SND-LHC/sndsw#151]
Hello, I am stater to use sndsw.
I am trying to install with following "On systems without access to CVMFS"
But I meet issue at step of "aliBuild build sndsw -c snddist"
I tried to install o2 But still can not use sndsw.
Can you help me?

Best Regards

error log is below

```
abc@abcui-MacBookAir sw % aliBuild build sndsw -c snddist
usage: aliBuild [-h] [-d] [-n]
                {analytics,architecture,build,clean,deps,doctor,init,version}
                ...
aliBuild: error: Default `o2' does not exists. Viable options:
- release
abc@abcui-MacBookAir sw % 

```

**Comment by ThomasRuf** [comment]
Try with
aliBuild build sndsw  --always-prefer-system -c $SNDDIST  --default release
 or use the alias:
sndBuild

best,
thomas

Von: 71year ***@***.***>
Gesendet: Mittwoch, 15. März 2023 04:57
An: SND-LHC/sndsw ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [SND-LHC/sndsw] aliBuild: error: Default `o2' does not exists (Issue #151)


Hello, I am stater to use sndsw.
I am trying to install with following "On systems without access to CVMFS"
But I meet issue at step of "aliBuild build sndsw -c snddist"
I tried to install o2 But still can not use sndsw.
Can you help me?

Best Regards

error log is below

***@***.*** sw % aliBuild build sndsw -c snddist

usage: aliBuild [-h] [-d] [-n]

                {analytics,architecture,build,clean,deps,doctor,init,version}

                ...

aliBuild: error: Default `o2' does not exists. Viable options:

- release

***@***.*** sw %

**Comment by olantwin** [comment]
This is an upstream issue in aliBuild with a know workaround (specify default `release`).
