### ISSUE TITLE
Need to update floor and remove overlap with Muon Filter

### ISSUE THREAD

**Issue by antonioiuliano2** [SND-LHC/sndsw#16]
Dear all,

running run_simScript.py with debug 2 leads to the following overlap:

Overlap ov00000: cave/floor_1 overlapping cave/volMuFilter_1 ovlp=2.03442

This overlap is between the floor and muon filter mother volume, and it was already present in the original version of the code by @abuonaura. When I have asked her about this, she told me that we need anyway to perform a more realistic implementation of the floor itself, before taking care of this overlap.

I put this issue here, in order not to forget this task.

**Comment by ThomasRuf** [comment]
I find the same overlap but when looking at the event display there is space between floor and the volFeBlocks.  Why do you need TGeoVolume *volMuFilter = new TGeoVolume("volMuFilter",MuFilterBox,air); ? Why not having only an assembly? Making a box of air inside the cave which is filled with air is strange.
I know see that you are using cave.geo, which is filled with vacuum. I think this should be replaced with caveWithAir.geo.

**Comment by antonioiuliano2** [comment]
You are right, I just avoid to abuse assemblies due to my past mistakes in nutaudet (I put too many assemblies in a class and they were not recognized by the Navigator in ProcessHits). In this particular case, the mother volume can be an assembly without any risk.

Thank you also for noticing the cave discrepancy, could you please apply that change yourself, since you know the geo files better?

**Comment by ThomasRuf** [comment]
since my idea of using a clone of sndsw is at the moment not working, can you please outline for me the procedure to make a pull request:
1) modify python/shipLHC_conf.py DONE
2) git commit python/shipLHC_conf.py -m "change to cave filled with air instead vacuum"
3) make a new branch, git branch TR
4) git push 

I am not sure about step 2,3,4.

**Comment by olantwin** [comment]
I would suggest first making sure you're on the correct branch before committing any changes.

So:

1. Make your modifications
2. `git checkout -b branchname` (e.g. `truf/flooroverlap`)
3. `git commit`
4. `git push origin branchname` (in the command line output github should offer making a pull request automatically)

`git branch branchname` creates a branch without switching to it (which has its uses, but I find is an unintuitive default)

**Comment by antonioiuliano2** [comment]
The overlap has been solved, the floor structure itself can be considered a future development and not an issue, so I am closing this thread.

**Comment by olantwin** [comment]
In #27? (Just for future reference, so we understand the links between issues, fixes etc.)

**Comment by antonioiuliano2** [comment]
That is correct, good idea to keep the reference, thank you.
