### ISSUE TITLE
build of sndsw broken

### ISSUE THREAD

**Issue by ThomasRuf** [SND-LHC/sndsw#18]
alibuild/aliBuild build sndsw -c snddist
....
+ cat
/media/disk0/SNDBuild/sw/SPECS/ubuntu2004_x86-64/sndsw/master-1/build.sh: line 151: bad substitution: no closing `}' in #%Module1.0
proc ModulesHelp { } {
  global version
  puts stderr "ALICE Modulefile for $PKGNAME $PKGVERSION-@@PKGREVISION@$PKGHASH@@"
....

**Comment by ThomasRuf** [comment]
seems to be fixed in new snddist

**Comment by olantwin** [comment]
Fixed by https://github.com/SND-LHC/snddist/commit/9373fb1984c6265cb8eb2bc0849b5d04442f3630 (and same issue fixed for FairShip in https://github.com/ShipSoft/shipdist/pull/67 ).
