### ISSUE TITLE
saveBasicParameters broken

### ISSUE THREAD

**Issue by ThomasRuf** [SND-LHC/sndsw#19]
After the last changes, I observe the following problem when running run_simScript:
Traceback (most recent call last):
  File "sndsw/macro/run_simScript.py", line 625, in <module>
    saveBasicParameters.execute("%s/geofile_full.%s.root" % (options.outputDir, tag),ship_geo)
  File "/media/disk0/SNDBuild/sw/ubuntu2004_x86-64/sndsw/master-1/python/saveBasicParameters.py", line 40, in execute
    o = retrieveGitTags(ox)
  File "/media/disk0/SNDBuild/sw/ubuntu2004_x86-64/sndsw/master-1/python/saveBasicParameters.py", line 15, in retrieveGitTags
    x = subprocess.check_output(['more',tmp]).replace('\n','')
TypeError: a bytes-like object is required, not 'str'

I checked, the tmp file exists, /media/disk0/SNDBuild/sw/ubuntu2004_x86-64/sndsw/master-1/.git/refs/remotes/origin/master 

executing subprocess.check_output(['more',tmp]) by hand gives: b'3c37ef1ebf4b3f6097917753f302f49c49a2ccc4\n' 
trying subprocess.check_output(['more',tmp]).replace('\n','') gives the error above.

I have no idea why this issue appears now. I can fix it with 
subprocess.check_output(['more',tmp]).decode().replace('\n','')

but would like to understand why it happens now and not 1hour before.

**Comment by olantwin** [comment]
This is strange. Usually the bytes/str problems occur when going from python2 to python3, but that wouldn't explain why it worked previously...

**Comment by olantwin** [comment]
Does this also affect FairShip?

**Comment by ThomasRuf** [comment]
can it be that the variable FAIRSHIP_HASH is not anymore defined but was defined before?

**Comment by ThomasRuf** [comment]
yes, we now have:
SNDSW_HASH=3c37ef1ebf4b3f6097917753f302f49c49a2ccc4
FAIRROOT_HASH=5d8d858165a4d263ff0648e391c3c8f2d416247e

**Comment by olantwin** [comment]
Yes, that's probably the reason.

For the time being, I'll define FAIRSHIP and FAIRSHIP_HASH again in the sndsw module-file. I should not have prematurely removed them.

**Comment by ThomasRuf** [comment]
how do we proceed? If we change environment variables from FairShip to sndsw, we have to change the code everywhere it is used. not very good. We can change the environment variable to an innocent name and use the same name in FairShip and sndsw, only change its value in the config script.

**Comment by olantwin** [comment]
I would suggest checking where we really need to use the environment variables (generally I would prefer to use them sparingly). E.g. in a log of cases where $FAIRSHIP is used, I think relative paths might be better.

Where they really are needed, we can rename the variables to something acceptable to both FairShip and sndsw, I think.
