### ISSUE TITLE
A lot of shadowed declarations in analysis classes (Wshadow)

### ISSUE THREAD

**Issue by olantwin** [SND-LHC/sndsw#192]
@cvilelahep

**Comment by cvilelahep** [comment]
I think I solved these, but maybe I haven't PRed those changes yet. I'll look into it tomorrow.

**Comment by olantwin** [comment]
Thanks!

At least as of 6ec8eeb03a7e572f5f9fc6bf8eeee75abce43432 it wasn't fixed, and I don't see anything in Simona's changes committed since that would change anything about these warnings.
