### ISSUE TITLE
Errors in HTCondor submissions

### ISSUE THREAD

**Issue by antonioiuliano2** [SND-LHC/sndsw#35]
Dear all,

as I discussed with @olantwin in Mattermost Software channel, I am struggling with making HTCondor submissions work.

It complains about a missing module "site" and it launches a long list of errors about FairROOT missing files and MC interface.

I attach the submission file, the command .sh file, and the error log.

Please tell me if you can think of any reason for this list of errors.

Best regards,
Antonio

P.S. I renamed the files in .LOG simply because github did not make me attach them with their original extensions .err, .sub and .sh

[neutrino.7050880.0_err.LOG](https://github.com/SND-LHC/sndsw/files/5708046/neutrino.7050880.0_err.LOG)
[neutrino_sh.LOG](https://github.com/SND-LHC/sndsw/files/5708048/neutrino_sh.LOG)
[neutrino_sub.LOG](https://github.com/SND-LHC/sndsw/files/5708050/neutrino_sub.LOG)

**Comment by olantwin** [comment]
I think the FairRoot errors is a symptom of the headers nor found by ROOT at runtime. Maybe we should check the `$ROOT_INCLUDE_PATH`?

Tip: Instead of attaching files, I would create a [gist](https://gist.github.com/) and quote the crucial lines here.

**Comment by ThomasRuf** [comment]
I think you are missing the correct FairShip setup from cvmfs. Could you just run some some basic script printing the environment? 
do you use something like eval `alienv load FairShip/latest-fairship` ? Other possibility, with alibuild, you can locally put the environment in a config.sh file, and then in your batch script execute something like source /afs/cern.ch/user/t/truf/Shipbuild-2018/config.sh.

**Comment by antonioiuliano2** [comment]
I launch
```bash
source /cvmfs/ship.cern.ch/SHiP-2021/latest/setUp.sh 
eval `alienv load sndsw/latest`
```
which is the configuration which worked in the past.

**Comment by olantwin** [comment]
Does it work for FairShip? Then we can maybe disentangle whether this is a problem in snddist or our CVMFS setup.

**Comment by antonioiuliano2** [comment]
I have just tested, in FairShip I unfortunately get the same errors.

**Comment by olantwin** [comment]
Then I suggest we continue discussing this in the FairShip/shipdist issue tracker, as this has nothing to do with sndsw.
