### ISSUE TITLE
Building from snddist instead of shipdist

### ISSUE THREAD

**Issue by antonioiuliano2** [SND-LHC/sndsw#5]
Dear @olantwin,

as far as I see, sndsw/alibuild.sh still builds from shipdist, even if you have prepared a separate fork snddist. 

Should this be updated to build from there? What is the recommended build recipe for this repository?

Best regards,
Antonio

**Comment by olantwin** [comment]
With #4, it should be possible for now to continue using shipdist. I will set up [wei/pull](https://github.com/wei/pull) for snddist as well to automatically pull in changes from shipdist.

One task for the first release obviously will be updating the README and instructions on how to build etc.

**Comment by olantwin** [comment]
This is now solved in snddist. I will also update the readme here.
