### ISSUE TITLE
Neutrino simulations crashing

### ISSUE THREAD

**Issue by antonioiuliano2** [SND-LHC/sndsw#51]
Dear all,

I report that simulations of CCDIS electron neutrino interactions in sndsw crash.
Looking at the error log, it does not seem to be GENIE, but Geant4 related:

```
 *** Break *** bus error

...........................................

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.

#8  0x00002ac6e88be7c1 in do_lookup_x () from /lib64/ld-linux-x86-64.so.2
#9  0x00002ac6e88bf09f in _dl_lookup_symbol_x () from /lib64/ld-linux-x86-64.so.2
#10 0x00002ac6e88c3dee in _dl_fixup () from /lib64/ld-linux-x86-64.so.2
#11 0x00002ac6e88cb9ea in _dl_runtime_resolve_xsave () from /lib64/ld-linux-x86-64.so.2
#12 0x00002ac729a59ff4 in G4HadronElastic::ApplyYourself(G4HadProjectile const&, G4Nucleus&) () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4processes.so
#13 0x00002ac729f7f5a6 in G4HadronElasticProcess::PostStepDoIt(G4Track const&, G4Step const&) () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4processes.s
o
#14 0x00002ac728dd5b4e in G4SteppingManager::InvokePSDIP(unsigned long) () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4tracking.so
#15 0x00002ac728dd6320 in G4SteppingManager::InvokePostStepDoItProcs() () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4tracking.so
#16 0x00002ac728dd3247 in G4SteppingManager::Stepping() () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4tracking.so
#17 0x00002ac728dde6a2 in G4TrackingManager::ProcessOneTrack(G4Track*) () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4tracking.so
#18 0x00002ac728b4ac10 in G4EventManager::DoProcessing(G4Event*) () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4event.so
#19 0x00002ac7288dcf45 in G4RunManager::ProcessOneEvent(int) () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4run.so
#20 0x00002ac7288db10b in G4RunManager::BeamOn(int, char const*, int) () from /cvmfs/ship.cern.ch/SHiP-2021/2020/November/16//sw//slc7_x86-64/GEANT4/v10.6.2-1/lib/libG4run.so
#21 0x00002ac724fc2544 in TG4RunManager::ProcessRun (this=0xb3d1950, nofEvents=10000) at /media/disk1/SHiPBuild/sw/SOURCES/GEANT4_VMC/v5-0-p5/v5-0-p5/source/run/src/TG4RunManager.cxx:551
#22 0x00002ac71c828509 in FairMCApplication::RunMC (this=0xa8b4d50, nofEvents=10000) at /media/disk1/SHiPBuild/sw/SOURCES/FairRoot/v18.4.2/v18.4.2/base/sim/FairMCApplication.cxx:461
#23 0x00002ac7089f805f in ?? ()
#24 0x0000000000000000 in ?? ()
```

Unfortunately, I do not have further information on this issue.

Best regards,
Antonio

**Comment by ThomasRuf** [comment]
mmh, bus error. Could it be that you reach some machine limits for example memory size? How frequently does it happen?  If you run the job exactly on the event where it crashed before, will it crash again?

**Comment by antonioiuliano2** [comment]
Thank you for your answer, Thomas.

It may be a memory issue, since the log reports:

	Partitionable Resources :    Usage  Request Allocated 
	   Cpus                 :     0.00        1         1 
	   Disk (KB)            :    56          56    208808 
	   Memory (MB)          :  1954        2000      2000
	   
or for another run:

005 (7336448.008.000) 02/17 02:49:50 Job terminated.
	(1) Normal termination (return value 135)
		Usr 1 03:43:06, Sys 0 00:01:18  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 1 03:43:06, Sys 0 00:01:18  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	63793  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	63793  -  Total Bytes Sent By Job
	928  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request Allocated 
	   Cpus                 :     1.00        1         1 
	   Disk (KB)            :    84          84    211790 
	   Memory (MB)          :  2198        2000      2000	   
	   
I will try to submit a new collection of run increasing the memory.

**Comment by ThomasRuf** [comment]
there could be a memory leak somewhere. you need to watch the evolution of the memory while the job runs. Or reduce number of events per job.

**Comment by antonioiuliano2** [comment]
Dear all,

I confirm that all jobs are ended without errors. I attach an exit log one job as an example. You can see that required memory is larger than 2000 MB (the maximum allowed one by default). I can close this particular issue, but as you suggested this may suggest a memory leak somewhere in FairROOT/FairShip. Thank you very much for your precious advice :)

	(1) Normal termination (return value 0)
		Usr 1 09:49:27, Sys 0 00:00:16  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 1 09:49:27, Sys 0 00:00:16  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	29386  -  Run Bytes Sent By Job
	928  -  Run Bytes Received By Job
	29386  -  Total Bytes Sent By Job
	1856  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request Allocated 
	   Cpus                 :     1.00       10        10 
	   Disk (KB)            :    52          45    285024 
	   Memory (MB)          :  2442       20000     20000
